/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maxneau
 */
public class interfaces extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfaces.class.getName());
int compteur=0 ;

    /**
     * Creates new form interfaces
     */
    public interfaces() {
        initComponents();
  
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoneTexte = new javax.swing.JLabel();
        Bouton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zoneTexte.setFont(new java.awt.Font("Herculanum", 2, 36)); // NOI18N
        zoneTexte.setText("BONJOUR");
        getContentPane().add(zoneTexte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        Bouton.setText("OKAYYYY");
        Bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonActionPerformed
       zoneTexte.setVisible(true);
       if (compteur==0) zoneTexte.setText ("alors mec tu date ");
        if (compteur==1) zoneTexte.setText ("Viens on va manger");
         if (compteur==2) zoneTexte.setText ("Du kombucha ");
compteur++;
    }//GEN-LAST:event_BoutonActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfaces().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton;
    private javax.swing.JLabel zoneTexte;
    // End of variables declaration//GEN-END:variables
}
