/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author maxneau
 */
public class interfaces extends JFrame {
    private List<Questions> questions;      // liste des questions
    private int indexQuestionCourante = 0; // question actuelle
    private int score = 0;                 // score du joueur

    public interfaces() {
        initComponents();
        initQuestions();           // créer les questions
        afficherQuestionCourante(); // afficher la première question
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoneTexte = new javax.swing.JLabel();
        Bouton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zoneTexte.setFont(new java.awt.Font("Herculanum", 2, 36)); // NOI18N
        zoneTexte.setText("Question1");
        getContentPane().add(zoneTexte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 180, 40));

        Bouton.setText("1");
        Bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 50));

        jButton1.setText("2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 50));

        jButton2.setText("3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 70, 50));

        jButton3.setText("4");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 70, 50));

        jButton4.setFont(new java.awt.Font("Herculanum", 0, 13)); // NOI18N
        jButton4.setText("Next question");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void traiterReponse(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void afficherQuestionCourante() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


private void initQuestions() {
    questions = new ArrayList<>();

    questions.add(new Question("Quel est la capitale de la France ?", "Londres", "Paris", "Berlin", "Madrid", 2));
    questions.add(new Question("Combien de jours dans une semaine ?", "5", "6", "7", "8", 3));
    questions.add(new Question("Quelle est la couleur du ciel ?", "Vert", "Bleu", "Rouge", "Jaune", 2));
    questions.add(new Question("2 + 2 = ?", "3", "4", "5", "22", 2));
    questions.add(new Question("Lequel est un langage de programmation ?", "HTML", "CSS", "Java", "JPEG", 3));
}

private void afficherQuestionCourante() {
    if (indexQuestionCourante >= questions.size()) {
        zoneTexte.setText("Quiz terminé ! Score final : " + score + " / " + questions.size());
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        return;
    }

    Question q = questions.get(indexQuestionCourante);
    zoneTexte.setText((indexQuestionCourante + 1) + ". " + q.getIntitule());
    jButton1.setText(q.getProposition1());
    jButton2.setText(q.getProposition2());
    jButton3.setText(q.getProposition3());
    jButton4.setText(q.getProposition4());

    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(true);
}
    private void traiterReponse(int numeroChoisi) {
    Question q = questions.get(indexQuestionCourante);

    if (numeroChoisi == q.getIndexBonneReponse()) {
        zoneTexte.setText("Bonne réponse !");
        score++;
    } else {
        String bonne = "";
        switch (q.getIndexBonneReponse()) {
            case 1: bonne = q.getProposition1(); break;
            case 2: bonne = q.getProposition2(); break;
            case 3: bonne = q.getProposition3(); break;
            case 4: bonne = q.getProposition4(); break;
        }
        zoneTexte.setText("Mauvaise réponse ! La bonne réponse était : " + bonne);
    }

    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
}

}


    private void BoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonActionPerformed
     indexQuestionCourante++;      // passer à la question suivante
afficherQuestionCourante();   
    }//GEN-LAST:event_BoutonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        traiterReponse(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       traiterReponse(2);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      traiterReponse(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      traiterReponse(4);
    }//GEN-LAST:event_jButton4ActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfaces().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel zoneTexte;
    // End of variables declaration//GEN-END:variables
// Variables pour gérer le quiz
private List<Questions> questions;
private int indexQuestionCourante = 0;
private int score = 0;                     // score du joueur

