/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maxneau
 */
public class interfaces_cadna extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfaces_cadna.class.getName());
private CadenasGame game = new CadenasGame();

    /**
     * Creates new form interfaces
     */
    public interfaces_cadna() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        haut1 = new javax.swing.JButton();
        haut2 = new javax.swing.JButton();
        haut3 = new javax.swing.JButton();
        haut4 = new javax.swing.JButton();
        bas5 = new javax.swing.JButton();
        bas6 = new javax.swing.JButton();
        bas7 = new javax.swing.JButton();
        bas8 = new javax.swing.JButton();
        NB1 = new javax.swing.JLabel();
        NB2 = new javax.swing.JLabel();
        NB3 = new javax.swing.JLabel();
        NB4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        haut1.setText("/\\");
            haut1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    haut1ActionPerformed(evt);
                }
            });
            getContentPane().add(haut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

            haut2.setText("/\\");
                haut2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        haut2ActionPerformed(evt);
                    }
                });
                getContentPane().add(haut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

                haut3.setText("/\\");
                    getContentPane().add(haut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

                    haut4.setText("/\\");
                        getContentPane().add(haut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

                        bas5.setText("\\/");
                        bas5.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bas5ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

                        bas6.setText("\\/");
                        getContentPane().add(bas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

                        bas7.setText("\\/");
                        getContentPane().add(bas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

                        bas8.setText("\\/");
                        getContentPane().add(bas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

                        NB1.setText("0");
                        getContentPane().add(NB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 130));

                        NB2.setText("0");
                        getContentPane().add(NB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 57, 60, 160));

                        NB3.setText("0");
                        getContentPane().add(NB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 57, 40, 160));

                        NB4.setText("0");
                        getContentPane().add(NB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 57, 50, 160));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void haut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haut1ActionPerformed

    private void haut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haut2ActionPerformed

    private void bas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bas5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bas5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfaces_cadna().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NB1;
    private javax.swing.JLabel NB2;
    private javax.swing.JLabel NB3;
    private javax.swing.JLabel NB4;
    private javax.swing.JButton bas5;
    private javax.swing.JButton bas6;
    private javax.swing.JButton bas7;
    private javax.swing.JButton bas8;
    private javax.swing.JButton haut1;
    private javax.swing.JButton haut2;
    private javax.swing.JButton haut3;
    private javax.swing.JButton haut4;
    // End of variables declaration//GEN-END:variables
}
