/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maxneau
 */
public class interfaces_cadna extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfaces_cadna.class.getName());


    /**
     * Creates new form interfaces
     */
    public interfaces_cadna() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        haut1 = new javax.swing.JButton();
        haut2 = new javax.swing.JButton();
        haut3 = new javax.swing.JButton();
        haut4 = new javax.swing.JButton();
        bas5 = new javax.swing.JButton();
        bas6 = new javax.swing.JButton();
        bas7 = new javax.swing.JButton();
        bas8 = new javax.swing.JButton();
        NB1 = new javax.swing.JLabel();
        NB2 = new javax.swing.JLabel();
        NB3 = new javax.swing.JLabel();
        NB4 = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        boutonTEST = new javax.swing.JButton();
        RESTART = new javax.swing.JButton();
        nbtentative = new javax.swing.JLabel();
        essairestant = new javax.swing.JLabel();
        NBchiffres_exact = new javax.swing.JLabel();
        NBchiffres_haut = new javax.swing.JLabel();
        NBchiffres_bas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        haut1.setText("/\\");
            haut1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    haut1ActionPerformed(evt);
                }
            });
            getContentPane().add(haut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

            haut2.setText("/\\");
                haut2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        haut2ActionPerformed(evt);
                    }
                });
                getContentPane().add(haut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

                haut3.setText("/\\");
                    getContentPane().add(haut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

                    haut4.setText("/\\");
                        getContentPane().add(haut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

                        bas5.setText("\\/");
                        bas5.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bas5ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

                        bas6.setText("\\/");
                        bas6.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bas6ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

                        bas7.setText("\\/");
                        getContentPane().add(bas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

                        bas8.setText("\\/");
                        getContentPane().add(bas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

                        NB1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
                        NB1.setText("0");
                        getContentPane().add(NB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 60));

                        NB2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
                        NB2.setText("0");
                        getContentPane().add(NB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, 100));

                        NB3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
                        NB3.setText("0");
                        getContentPane().add(NB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 40, 90));

                        NB4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
                        NB4.setText("0");
                        getContentPane().add(NB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 50, 70));

                        intro.setText("trouve le code et tu seras riche!");
                        getContentPane().add(intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

                        boutonTEST.setText("Tester");
                        boutonTEST.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                boutonTESTActionPerformed(evt);
                            }
                        });
                        getContentPane().add(boutonTEST, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

                        RESTART.setText("Recommencer ");
                        RESTART.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                RESTARTActionPerformed(evt);
                            }
                        });
                        getContentPane().add(RESTART, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

                        nbtentative.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
                        nbtentative.setText("0/5");
                        getContentPane().add(nbtentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 70, 80));

                        essairestant.setText("Essai restant: ");
                        getContentPane().add(essairestant, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

                        NBchiffres_exact.setText("Nombre de chiffres exact :            0");
                        getContentPane().add(NBchiffres_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

                        NBchiffres_haut.setText("Nombre de chiffres trop hauts :     0");
                        getContentPane().add(NBchiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, 20));

                        NBchiffres_bas.setText("Nombre de chiffres trop bas :        0");
                        getContentPane().add(NBchiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void haut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haut1ActionPerformed

    private void haut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haut2ActionPerformed

    private void bas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bas5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bas5ActionPerformed

    private void bas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bas6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bas6ActionPerformed

    private void boutonTESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonTESTActionPerformed
   


    }//GEN-LAST:event_boutonTESTActionPerformed

    private void RESTARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTARTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESTARTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfaces_cadna().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NB1;
    private javax.swing.JLabel NB2;
    private javax.swing.JLabel NB3;
    private javax.swing.JLabel NB4;
    private javax.swing.JLabel NBchiffres_bas;
    private javax.swing.JLabel NBchiffres_exact;
    private javax.swing.JLabel NBchiffres_haut;
    private javax.swing.JButton RESTART;
    private javax.swing.JButton bas5;
    private javax.swing.JButton bas6;
    private javax.swing.JButton bas7;
    private javax.swing.JButton bas8;
    private javax.swing.JButton boutonTEST;
    private javax.swing.JLabel essairestant;
    private javax.swing.JButton haut1;
    private javax.swing.JButton haut2;
    private javax.swing.JButton haut3;
    private javax.swing.JButton haut4;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel nbtentative;
    // End of variables declaration//GEN-END:variables
}
